import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/ui/Navbar/Navbar";
import { items } from "@/lib/items";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taskfy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AntdRegistry>
        <body className={inter.className}>
          <Navbar items={items} />
          {children}
        </body>
      </AntdRegistry>
    </html>
  );
}
